In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,5,6,6],dtype=np.float16)

In [7]:
arr.itemsize

2

In [15]:
arr = np.array([2,3,5,6,6,7],dtype=np.float32)

In [14]:
arr.itemsize

4

<h2>Indexing and Slicing</h2>

In [49]:
arr = np.array([23,
                67,
                89,
                45,
                56,
                78,
                34,
                89,
                20])

In [50]:
arr.ndim

1

In [42]:
arr

array([23, 67, 89, 45, 56, 78, 34, 89, 20])

In [23]:
arr[2]

np.int64(89)

In [21]:
for i in arr:
    print(i)

23
67
89
45


In [36]:
arr[2:7]

array([89, 45, 56, 78, 34])

2D Matrix

In [37]:
matrix = np.array(
    [[2,4,3],
     [6,5,9],
     [0,4,8]]
)

In [51]:
matrix.ndim

2

In [38]:
print(matrix)

[[2 4 3]
 [6 5 9]
 [0 4 8]]


In [54]:
matrix[2][1:3]

array([4, 8])

In [70]:
matrix = np.array(
    [[2,4,3],
     [6,5,9],
     [0,4,8]]
)

In [79]:
matrix[1:,0:2]

array([[6, 5],
       [0, 4]])

<h2>Reshaping & Flattening Arrays</h2>

In [80]:
arr = np.arange(6)

In [81]:
arr

array([0, 1, 2, 3, 4, 5])

In [85]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [90]:
temp = matrix.flatten()

In [91]:
temp

array([2, 4, 3, 6, 5, 9, 0, 4, 8])

In [88]:
matrix.ravel()

array([2, 4, 3, 6, 5, 9, 0, 4, 8])

In [89]:
matrix

array([[2, 4, 3],
       [6, 5, 9],
       [0, 4, 8]])

<h2>Mathematical Operations</h2>

In [98]:
a = np.array([2,4,2])
b = np.array([5,8,3])

a_ = np.array([[3],
               [2],
               [1]])

<h3 style="color:green;">Vector Calculation</h3>

In [99]:
a+b

array([ 7, 12,  5])

In [100]:
a-b

array([-3, -4, -1])

In [101]:
a*b

array([10, 32,  6])

In [102]:
np.add(a,b)

array([ 7, 12,  5])

In [103]:
np.multiply(a,b)

array([10, 32,  6])

In [104]:
np.subtract(a,b)

array([-3, -4, -1])

In [105]:
np.divide(a,b)

array([0.4       , 0.5       , 0.66666667])

<h3 style="color:green;">Scaler Calculation</h3>

In [106]:
a * 3

array([ 6, 12,  6])

In [107]:
a - 5

array([-3, -1, -3])

In [108]:
a + 3

array([5, 7, 5])

<h3>Aggregation Functions</h3>

In [109]:
arr = np.array([34,23,67,45,56,29])

In [110]:
np.sum(arr)

np.int64(254)

In [111]:
np.mean(arr)

np.float64(42.333333333333336)

In [112]:
np.median(arr)

np.float64(39.5)

In [113]:
np.std(arr)

np.float64(15.402020069530563)

In [114]:
np.var(arr)

np.float64(237.22222222222226)

In [115]:
np.min(arr)

np.int64(23)

In [116]:
np.max(arr)

np.int64(67)

In [117]:
np.argmin(arr)

np.int64(1)

In [119]:
np.argmax(matrix)

np.int64(5)

In [120]:
matrix

array([[2, 4, 3],
       [6, 5, 9],
       [0, 4, 8]])

<h3>Boolean & Filtering</h3>

In [121]:
arr = np.array([34,23,67,45,56,29])

In [122]:
arr > 30

array([ True, False,  True,  True,  True, False])

In [ ]:
arr[(arr > 30) & (arr < 60) & (arr != 45)]

array([34, 56])

In [130]:
(arr > 30) & (arr < 60) & (arr != 45)

array([ True, False, False, False,  True, False])