In [1]:
import numpy as np

Sorting (return the copy of sorted array)

In [4]:
arr = np.array([3,5,2,8,6,1])

sorted_arr = np.sort(arr)

In [7]:
sorted_arr

array([1, 2, 3, 5, 6, 8])

Returns the indices of sorted array

In [6]:
np.argsort(arr)

array([5, 2, 0, 1, 4, 3])

we can put if-else like condition for array

In [8]:
np.where(arr>5,"High","Low")

array(['Low', 'Low', 'Low', 'High', 'High', 'Low'], dtype='<U4')

In [9]:
np.where(arr>5)

(array([3, 4]),)

In [13]:
sorted_arr

array([1, 2, 3, 5, 6, 8])

Returns you the position of index , where you can insert elements

In [14]:
np.searchsorted(sorted_arr,4)

np.int64(3)

In [15]:
np.searchsorted(sorted_arr,[4,9])

array([3, 6])

In [16]:
arr1 = np.array([1,2,2,3,2,4,4,5,3])

Remove duplicacy from the array

In [17]:
np.unique(arr1)

array([1, 2, 3, 4, 5])

In [20]:
np.unique(arr1,return_counts=True)

(array([1, 2, 3, 4, 5]), array([1, 3, 2, 2, 1]))

Concatenate

In [21]:
a = np.array([[1,2]])
b = np.array([[3,4]])

In [25]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4]])

vstack

In [26]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [27]:
np.hstack((a,b))

array([[1, 2, 3, 4]])

In [28]:
arr

array([3, 5, 2, 8, 6, 1])

split()

In [34]:
np.split(arr,3)

[array([3, 5]), array([2, 8]), array([6, 1])]

copy()

In [35]:
a = np.array([1,2,3])

b = a.copy()

In [38]:
a[1] = 4

In [39]:
a

array([1, 4, 3])

In [40]:
b

array([1, 2, 3])

view()

In [41]:
a = np.array([3,4,2])

b = a.view()

b

array([3, 4, 2])

In [42]:
a[1] = 3

In [43]:
b

array([3, 3, 2])

In [46]:
type(arr)

numpy.ndarray

In [45]:
arr2 = np.asarray([3,4,3])
type(arr2)

numpy.ndarray

In [72]:
arr3 = np.array([1,3,2,4,np.nan,5,6,np.nan])

In [55]:
np.isnan(arr3).sum()

np.int64(2)

In [73]:
np.mean(arr3)

np.float64(nan)

In [75]:
np.median(arr3)

np.float64(nan)

In [74]:
np.nanmean(arr3)

np.float64(3.5)

In [76]:
np.nanmedian(arr3)

np.float64(3.5)

In [77]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a,b)

np.int64(32)

In [82]:
mat1 = np.array(
    [[1,2,3],
    [2,1,2],
    [2,2,1]])

mat2 = np.array([
[2,2,1],
[2,3,4],
[2,3,5]])


np.dot(mat1,mat2)

array([[12, 17, 24],
       [10, 13, 16],
       [10, 13, 15]])

In [81]:
mat1 @ mat2

array([[12, 17, 24],
       [10, 13, 16],
       [10, 13, 15]])

In [88]:
inv_mat1 = np.linalg.inv(mat1)

In [98]:
A = np.array([[1,2],
[3,4]])

In [99]:
A

array([[1, 2],
       [3, 4]])

In [94]:
inv_A = np.linalg.inv(A)

In [95]:
inv_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [97]:
A * inv_A

array([[-2. ,  2. ],
       [ 4.5, -2. ]])