In [1]:
import random

In [2]:
import numpy as np

In [38]:
np.random.rand()

0.8709315311862219

In [39]:
rng = np.random.default_rng()

In [49]:
rng.random()

0.26214676026624717

In [65]:
rng.integers(1,7)

np.int64(1)

In [82]:
rng.normal(2,3)

0.10103988707769307

In [83]:
fruits = ["Apple","guava","banana","kivi"]

In [96]:
rng.choice(fruits)

np.str_('banana')

In [119]:
rng.random((3,3,3))

array([[[0.17350292, 0.74745115, 0.98050061],
        [0.56209815, 0.96848418, 0.76471139],
        [0.74751028, 0.32237406, 0.65714703]],

       [[0.64486064, 0.89711605, 0.79376167],
        [0.22984437, 0.96817511, 0.66062566],
        [0.97880852, 0.56327577, 0.59636032]],

       [[0.83021384, 0.10930536, 0.88934999],
        [0.0092767 , 0.38397778, 0.0371273 ],
        [0.41880363, 0.21615262, 0.69147973]]])

In [142]:
rng.integers(1,100,(3,3))

array([[29, 85, 27],
       [57, 86, 90],
       [82, 80, 82]])

In [143]:
fruits

['Apple', 'guava', 'banana', 'kivi']

In [153]:
rng.choice(fruits,3)

array(['kivi', 'banana', 'Apple'], dtype='<U6')

In [171]:
rng.choice(fruits,size=4,replace=False)

array(['banana', 'Apple', 'guava', 'kivi'], dtype='<U6')

In [174]:
arr = np.array([1,2,3,4,5,6])

rng.shuffle(arr)

In [175]:
arr

array([5, 1, 3, 2, 4, 6])

In [179]:
arr = np.array([1,2,3,4,5,6])

new_arr = rng.permutation(arr)

In [180]:
arr

array([1, 2, 3, 4, 5, 6])

Uniform distribution

In [203]:
rng.uniform(10,20,size=(2,3))

array([[11.89075468, 17.24756357, 15.12172371],
       [10.84139127, 12.27338822, 14.59728283]])

binomial distribution

In [271]:
rng.binomial(n=10,p=0.5,size=5)

array([2, 3, 5, 3, 4])

In [304]:
rng = np.random.default_rng(12)

rng.integers(1,10,5)

array([6, 3, 9, 9, 1])

In [306]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 10.8 MB 1.6 MB/s eta 0:00:01
     |████████████████████████████████| 510 kB 2.0 MB/s eta 0:00:01
     |████████████████████████████████| 348 kB 1.7 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [307]:
import pandas as pd

In [309]:
n = 100
df = pd.DataFrame({
    "customer_id":rng.integers(1000,9999,size=n),
    "salary":np.round(rng.uniform(25000,120000,size=n),2),
    "city":rng.choice(['delhi','mumbai','lucknow','banglore','pune'],size=n),
    "is_active":rng.choice([True,False],size=n),
    "join_date":pd.to_datetime("2023-01-01") + pd.to_timedelta(rng.integers(0,365,size=n),unit="D"),
    "department":rng.choice(['HR','IT','Finance','Sales'],size=n),
    "remarks":rng.choice(['good','averge','excellent','pending'],size=n),
    'rating':rng.choice([1,2,3,4,5,np.nan],size=n)
})

In [312]:
df.head(10)

,customer_id,salary,city,is_active,join_date,department,remarks,rating
0,2999,114129.74,mumbai,False,2023-12-22,IT,averge,NaN
1,5847,70493.95,pune,True,2023-07-29,Finance,averge,4.0
2,8973,66331.79,lucknow,True,2023-12-27,Finance,pending,3.0
3,3742,107842.81,lucknow,False,2023-08-01,Sales,excellent,3.0
4,3823,106449.32,lucknow,True,2023-01-06,HR,pending,5.0
5,5899,110199.23,mumbai,True,2023-03-19,Finance,averge,1.0
6,5917,27142.35,delhi,False,2023-08-08,HR,pending,1.0
7,2804,119583.59,banglore,False,2023-02-06,HR,pending,NaN
8,6080,90198.80,lucknow,True,2023-04-03,Finance,pending,4.0
9,9089,110768.18,banglore,False,2023-04-07,Finance,good,2.0
